name: Integration Tests

env:
  host: ${{ secrets.HOST }}
  databaseUser: ${{ secrets.USERNAME }}
  databasePassword: ${{ secrets.PASSWORD }}
  databasePort: ${{ secrets.PORT }}
  databaseName: ${{ secrets.DATABASE }}

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - kusu

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo systemctl start mysql.service
          sudo mysql --user="${{ env.USERNAME }}" --password="${{ env.PASSWORD }}" -e "CREATE DATABASE IF NOT EXISTS ${{ env.DATABASE }};"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
  
