name: Integration Tests
 
env:
  DB_HOST: ${{ secrets.SQL.host }}
  DB_USER: ${{ secrets.SQL.databaseUser}}
  DB_PASS: ${{ secrets.SQL.databasePassword }}
  DB_PORT: ${{ secrets.SQL.databasePort }}
  DB_NAME: ${{ secrets.SQL.databaseName }}
 
on:
  pull_request:
    branches:
      - main
  
  push:
    branches:
      - kusu
 
jobs:
  integration-test:
    runs-on: ubuntu-latest
 
    steps:
      - name : Install MySQL
        run: |
          sudo apt-get update
          sudo systemctl start mysql.service
          sudo mysql --user=${{ secrets.SQL.databaseUser }} --password=${{ secrets.SQL.databasePassword}} -e "CREATE DATABASE IF NOT EXISTS ${DB_NAME};"
 
      - name: Checkout Repository
        uses: actions/checkout@v2
 
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
 
      - name: Install Dependencies
        run: npm install
 
      - name: Run Tests
        run: npm test
